@startuml
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title MPAIO: optimum batching on a 4 core system

map SHM.block0 {
}
map SHM.block1 {
}
map SHM.block2 {
}
map SHM.block3 {
}
map core.0 {
}
map core.1 {
}
map core.2 {
}
map core.3 {
}
map worker.0 {
}
map worker.1 {
}
map worker.2 {
}
map worker.3 {
}

SHM.block0 <-- core.0 : process
SHM.block1 <-- core.1 : process
SHM.block2 <-- core.2 : process
SHM.block3 <-- core.3 : process

core.0 --> worker.0 : process_callback
core.1 --> worker.1 : process_callback
core.2 --> worker.2 : process_callback
core.3 --> worker.3 : process_callback

@enduml