@startuml
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title MPAIO: optimum batching on a 4 core system

map SHM.block0 {
}
map SHM.block1 {
}
map SHM.block2 {
}
map SHM.block3 {
}
map user {
event loop running in main process\nawaits the output of the workers =>
}

map worker.0 {
}
map worker.1 {
}
map worker.2 {
}
map worker.3 {
}

SHM.block0 <-- worker.0 : process
SHM.block1 <-- worker.1 : process
SHM.block2 <-- worker.2 : process
SHM.block3 <-- worker.3 : process

worker.0 --> worker.0 : core-0
worker.1 --> worker.1 : core-1
worker.2 --> worker.2 : core-2
worker.3 --> worker.3 : core-3

worker.0 --> user : process_callback
worker.1 --> user : process_callback
worker.2 --> user : process_callback
worker.3 --> user : process_callback

@enduml