name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 mypy
          pip install -e .
      - name: Test with pytest
        run: |
          flake8 --max-line-length=120 src examples tests
          mypy src tests
          coverage run -m pytest tests
          coverage report --fail-under=95
